### ISSUE TITLE
Compilation OpenChange/MAPIStorePropertySelectors.m is failed

### ISSUE THREAD

**Issue by sibskull** [inverse-inc/sogo#124]
~~~~
 Compiling file MAPIStorePropertySelectors.m ...
In file included from MAPIStorePropertySelectors.m:6:
In file included from ./MAPIStorePropertySelectors.h:19:
./MAPIStoreObject.h:71:32: warning: declaration of 'struct mapistore_property_data' will not be visible outside of this function [-Wvisibility]
- (int) getProperties: (struct mapistore_property_data *) data
                               ^
MAPIStorePropertySelectors.m:66519:3: error: initializer element is not a compile-time constant
  @selector (getPidTagAttributeHidden:inMemCtx:),
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
~~~~

**Comment by extrafu** [comment]
You need openchange 2.4-zentyal13 to compile SOGo with OpenChange support. Get it from https://github.com/zentyal/openchange/releases

**Comment by sibskull** [comment]
Try to build with 2.4-zentyal13 (and 2.4-zentyal16 too). Same error.
